/*
 * This file is generated by jOOQ.
 */
package com.devproserv.courses.jooq;


import com.devproserv.courses.jooq.tables.Archive;
import com.devproserv.courses.jooq.tables.Courses;
import com.devproserv.courses.jooq.tables.Lecturers;
import com.devproserv.courses.jooq.tables.StudentCourses;
import com.devproserv.courses.jooq.tables.Students;
import com.devproserv.courses.jooq.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>coursedb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARCHIVE_FK_ARCHIVE_STUDENT_COURSES1_IDX = Indexes0.ARCHIVE_FK_ARCHIVE_STUDENT_COURSES1_IDX;
    public static final Index ARCHIVE_PRIMARY = Indexes0.ARCHIVE_PRIMARY;
    public static final Index COURSES_FK_COURSES_LECTURERS1_IDX = Indexes0.COURSES_FK_COURSES_LECTURERS1_IDX;
    public static final Index COURSES_PRIMARY = Indexes0.COURSES_PRIMARY;
    public static final Index LECTURERS_FK_LECTURERS_USERS1_IDX = Indexes0.LECTURERS_FK_LECTURERS_USERS1_IDX;
    public static final Index LECTURERS_PRIMARY = Indexes0.LECTURERS_PRIMARY;
    public static final Index STUDENTS_FK_STUDENTS_USERS1_IDX = Indexes0.STUDENTS_FK_STUDENTS_USERS1_IDX;
    public static final Index STUDENTS_PRIMARY = Indexes0.STUDENTS_PRIMARY;
    public static final Index STUDENT_COURSES_FK_STUDENT_COURSES_STUDENTS1_IDX = Indexes0.STUDENT_COURSES_FK_STUDENT_COURSES_STUDENTS1_IDX;
    public static final Index STUDENT_COURSES_PRIMARY = Indexes0.STUDENT_COURSES_PRIMARY;
    public static final Index USERS_LOGIN_UNIQUE = Indexes0.USERS_LOGIN_UNIQUE;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_USER_ID_UNIQUE = Indexes0.USERS_USER_ID_UNIQUE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARCHIVE_FK_ARCHIVE_STUDENT_COURSES1_IDX = Internal.createIndex("fk_archive_student_courses1_idx", Archive.ARCHIVE, new OrderField[] { Archive.ARCHIVE.COURSE_ID, Archive.ARCHIVE.STUD_ID }, false);
        public static Index ARCHIVE_PRIMARY = Internal.createIndex("PRIMARY", Archive.ARCHIVE, new OrderField[] { Archive.ARCHIVE.COURSE_ID, Archive.ARCHIVE.STUD_ID }, true);
        public static Index COURSES_FK_COURSES_LECTURERS1_IDX = Internal.createIndex("fk_courses_lecturers1_idx", Courses.COURSES, new OrderField[] { Courses.COURSES.LECT_ID }, false);
        public static Index COURSES_PRIMARY = Internal.createIndex("PRIMARY", Courses.COURSES, new OrderField[] { Courses.COURSES.COURSE_ID, Courses.COURSES.LECT_ID }, true);
        public static Index LECTURERS_FK_LECTURERS_USERS1_IDX = Internal.createIndex("fk_lecturers_users1_idx", Lecturers.LECTURERS, new OrderField[] { Lecturers.LECTURERS.LECT_ID }, false);
        public static Index LECTURERS_PRIMARY = Internal.createIndex("PRIMARY", Lecturers.LECTURERS, new OrderField[] { Lecturers.LECTURERS.LECT_ID }, true);
        public static Index STUDENTS_FK_STUDENTS_USERS1_IDX = Internal.createIndex("fk_students_users1_idx", Students.STUDENTS, new OrderField[] { Students.STUDENTS.STUD_ID }, false);
        public static Index STUDENTS_PRIMARY = Internal.createIndex("PRIMARY", Students.STUDENTS, new OrderField[] { Students.STUDENTS.STUD_ID }, true);
        public static Index STUDENT_COURSES_FK_STUDENT_COURSES_STUDENTS1_IDX = Internal.createIndex("fk_student_courses_students1_idx", StudentCourses.STUDENT_COURSES, new OrderField[] { StudentCourses.STUDENT_COURSES.STUD_ID }, false);
        public static Index STUDENT_COURSES_PRIMARY = Internal.createIndex("PRIMARY", StudentCourses.STUDENT_COURSES, new OrderField[] { StudentCourses.STUDENT_COURSES.COURSE_ID, StudentCourses.STUDENT_COURSES.STUD_ID }, true);
        public static Index USERS_LOGIN_UNIQUE = Internal.createIndex("login_UNIQUE", Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.USER_ID }, true);
        public static Index USERS_USER_ID_UNIQUE = Internal.createIndex("user_id_UNIQUE", Users.USERS, new OrderField[] { Users.USERS.USER_ID }, true);
    }
}
