/*
 * This file is generated by jOOQ.
 */
package com.devproserv.courses.jooq;


import com.devproserv.courses.jooq.tables.Archive;
import com.devproserv.courses.jooq.tables.Courses;
import com.devproserv.courses.jooq.tables.Lecturers;
import com.devproserv.courses.jooq.tables.StudentCourses;
import com.devproserv.courses.jooq.tables.Students;
import com.devproserv.courses.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in coursedb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>coursedb.archive</code>.
     */
    public static final Archive ARCHIVE = com.devproserv.courses.jooq.tables.Archive.ARCHIVE;

    /**
     * The table <code>coursedb.courses</code>.
     */
    public static final Courses COURSES = com.devproserv.courses.jooq.tables.Courses.COURSES;

    /**
     * The table <code>coursedb.lecturers</code>.
     */
    public static final Lecturers LECTURERS = com.devproserv.courses.jooq.tables.Lecturers.LECTURERS;

    /**
     * The table <code>coursedb.students</code>.
     */
    public static final Students STUDENTS = com.devproserv.courses.jooq.tables.Students.STUDENTS;

    /**
     * The table <code>coursedb.student_courses</code>.
     */
    public static final StudentCourses STUDENT_COURSES = com.devproserv.courses.jooq.tables.StudentCourses.STUDENT_COURSES;

    /**
     * The table <code>coursedb.users</code>.
     */
    public static final Users USERS = com.devproserv.courses.jooq.tables.Users.USERS;
}
