/*
 * This file is generated by jOOQ.
 */
package com.devproserv.courses.jooq.tables;


import com.devproserv.courses.jooq.Coursedb;
import com.devproserv.courses.jooq.Indexes;
import com.devproserv.courses.jooq.Keys;
import com.devproserv.courses.jooq.tables.records.CoursesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Courses extends TableImpl<CoursesRecord> {

    private static final long serialVersionUID = 564979766;

    /**
     * The reference instance of <code>coursedb.courses</code>
     */
    public static final Courses COURSES = new Courses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoursesRecord> getRecordType() {
        return CoursesRecord.class;
    }

    /**
     * The column <code>coursedb.courses.course_id</code>.
     */
    public final TableField<CoursesRecord, Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>coursedb.courses.name</code>.
     */
    public final TableField<CoursesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>coursedb.courses.description</code>.
     */
    public final TableField<CoursesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>coursedb.courses.lect_id</code>.
     */
    public final TableField<CoursesRecord, Integer> LECT_ID = createField("lect_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>coursedb.courses</code> table reference
     */
    public Courses() {
        this(DSL.name("courses"), null);
    }

    /**
     * Create an aliased <code>coursedb.courses</code> table reference
     */
    public Courses(String alias) {
        this(DSL.name(alias), COURSES);
    }

    /**
     * Create an aliased <code>coursedb.courses</code> table reference
     */
    public Courses(Name alias) {
        this(alias, COURSES);
    }

    private Courses(Name alias, Table<CoursesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Courses(Name alias, Table<CoursesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Courses(Table<O> child, ForeignKey<O, CoursesRecord> key) {
        super(child, key, COURSES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Coursedb.COURSEDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COURSES_FK_COURSES_LECTURERS1_IDX, Indexes.COURSES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CoursesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COURSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CoursesRecord> getPrimaryKey() {
        return Keys.KEY_COURSES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoursesRecord>> getKeys() {
        return Arrays.<UniqueKey<CoursesRecord>>asList(Keys.KEY_COURSES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CoursesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CoursesRecord, ?>>asList(Keys.FK_COURSES_LECTURERS1);
    }

    public Lecturers lecturers() {
        return new Lecturers(this, Keys.FK_COURSES_LECTURERS1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Courses as(String alias) {
        return new Courses(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Courses as(Name alias) {
        return new Courses(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Courses rename(String name) {
        return new Courses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Courses rename(Name name) {
        return new Courses(name, null);
    }
}
