/*
 * This file is generated by jOOQ.
 */
package com.devproserv.courses.jooq.tables.records;


import com.devproserv.courses.jooq.tables.Lecturers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturersRecord extends UpdatableRecordImpl<LecturersRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1415044346;

    /**
     * Setter for <code>coursedb.lecturers.lect_id</code>.
     */
    public void setLectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coursedb.lecturers.lect_id</code>.
     */
    public Integer getLectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coursedb.lecturers.degree</code>.
     */
    public void setDegree(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>coursedb.lecturers.degree</code>.
     */
    public String getDegree() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Lecturers.LECTURERS.LECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Lecturers.LECTURERS.DEGREE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDegree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDegree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value1(Integer value) {
        setLectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord value2(String value) {
        setDegree(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturersRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturersRecord
     */
    public LecturersRecord() {
        super(Lecturers.LECTURERS);
    }

    /**
     * Create a detached, initialised LecturersRecord
     */
    public LecturersRecord(Integer lectId, String degree) {
        super(Lecturers.LECTURERS);

        set(0, lectId);
        set(1, degree);
    }
}
