/*
 * This file is generated by jOOQ.
 */
package com.devproserv.courses.jooq.tables.records;


import com.devproserv.courses.jooq.tables.Students;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsRecord extends UpdatableRecordImpl<StudentsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -112682046;

    /**
     * Setter for <code>coursedb.students.stud_id</code>.
     */
    public void setStudId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coursedb.students.stud_id</code>.
     */
    public Integer getStudId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coursedb.students.faculty</code>.
     */
    public void setFaculty(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>coursedb.students.faculty</code>.
     */
    public String getFaculty() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Students.STUDENTS.STUD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Students.STUDENTS.FACULTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStudId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFaculty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStudId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFaculty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value1(Integer value) {
        setStudId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value2(String value) {
        setFaculty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsRecord
     */
    public StudentsRecord() {
        super(Students.STUDENTS);
    }

    /**
     * Create a detached, initialised StudentsRecord
     */
    public StudentsRecord(Integer studId, String faculty) {
        super(Students.STUDENTS);

        set(0, studId);
        set(1, faculty);
    }
}
